version: 2.1

commands:
  get_test_results_path:
    parameters:
      path:
        type: string
        default: "/tmp/test-results"
    steps:
      - run: echo << parameters.path >>
  store_results:
    parameters:
      path:
        type: string
        default: "/tmp/test-results"
    steps:
      - store_test_results:
          path: << parameters.path >>
      - store_artifacts:
          path: << parameters.path >>

# reusable 'executor' object for jobs
executors:
  go:
    shell: /usr/bin/env bash -euo pipefail -c 
    docker:
      - image: circleci/golang:1.13.3

jobs:
  go-test:
    executor: go
    steps:
      - checkout
      - run: mkdir -p get_test_results_path

      - restore_cache: # restore cache if it exists
          keys:
            - go-retryablehttp-modcache-v1-{{ checksum "go.mod" }}

      - run: go mod download

      # save go module cache if the go.mod file has changed
      - save_cache:
          key: go-retryablehttp-modcache-v1-{{ checksum "go.mod" }}
          paths:
            - "/go/pkg/mod"

      # check go fmt output because it does not report non-zero when there are fmt changes
      - run:
          name: check go fmt
          command: |
            files=$(go fmt ./...)
            if [ -n "$files" ]; then
              echo "The following file(s) do not conform to go fmt:"
              echo "$files"
              exit 1
            fi
      # run go tests with gotestsum
      - run: |
          PACKAGE_NAMES=$(go list ./...)
          gotestsum --format=short-verbose --junitfile get_test_results_path/gotestsum-report.xml -- $PACKAGE_NAMES

      - run: store_results

workflows:
  test-and-build:
    jobs:
      - go-test

